public class ReportTemplate
{
    public string Title { get; set; }
    public string Header { get; set; }
    public string Footer { get; set; }
    public string DateFormat { get; set; }
    public string[] ColumnHeaders { get; set; }

    public ReportTemplate()
    {
        Title = "Attendance Report";
        Header = "Attendance Records";
        Footer = "Generated by Attendance Management System";
        DateFormat = "MM/dd/yyyy";
        ColumnHeaders = new string[] { "SrNo", "Name", "Date" };
    }
}